<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Basecamp\Module'                        => __DIR__ . '/Module.php',
    'Basecamp\Controller\ProjectsController' => __DIR__ . '/src/Basecamp/Controller/ProjectsController.php',
    'BasecampTest\Framework\TestCase'        => __DIR__ . '/tests/Basecamp/Framework/TestCase.php',
    'BasecampTest\SampleTest'                => __DIR__ . '/tests/Basecamp/SampleTest.php',
);